version: '3.8'
services: 
  postgredb:
    container_name: apiPostgresDB
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=teerapat
      - POSTGRES_PASSWORD=admin1234
    ports:
      - '5050:5432'
    volumes:
      - pgdata:/var/lib/lib/postgresql/data
volumes:
  pgdata: