// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/posts/ent/post"
	"api/posts/ent/schema"
	"api/posts/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[0].Descriptor()
	// post.DefaultTitle holds the default value on creation for the title field.
	post.DefaultTitle = postDescTitle.Default.(string)
	// postDescBody is the schema descriptor for body field.
	postDescBody := postFields[1].Descriptor()
	// post.DefaultBody holds the default value on creation for the body field.
	post.DefaultBody = postDescBody.Default.(string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
}
