// Code generated by ent, DO NOT EDIT.

package ent

import (
	"di-practice/ent/schema"
	"di-practice/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTitle is the schema descriptor for title field.
	userDescTitle := userFields[2].Descriptor()
	// user.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	user.TitleValidator = userDescTitle.Validators[0].(func(string) error)
	// userDescBody is the schema descriptor for body field.
	userDescBody := userFields[3].Descriptor()
	// user.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	user.BodyValidator = userDescBody.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[1].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
}
