definitions:
  model.Post:
    properties:
      body:
        type: string
      id:
        type: integer
      title:
        type: string
      userId:
        type: integer
    type: object
info:
  contact: {}
paths:
  /check-posts:
    get:
      consumes:
      - '*/*'
      description: get a posts from database or web.
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            items:
              $ref: '#/definitions/model.Post'
            type: array
      summary: Show a posts.
      tags:
      - Posts
  /posts:
    get:
      consumes:
      - '*/*'
      description: get a posts from database or web.
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            items:
              $ref: '#/definitions/model.Post'
            type: array
      summary: Show a posts.
      tags:
      - Posts
swagger: "2.0"
